spring:
  application:
    name: UACS-BULLETIN
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/uacs?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    appname: UACS-BULLETIN
    prefer-ip-address: true
server:
  port: 7200
feign:
  hystrix:
    enabled: true