spring:
  application:
    name: UACS-ASSOCIATION
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost/uacs?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    appname: UACS-ASSOCIATION
    prefer-ip-address: true
server:
  port: 7100
feign:
  hystrix:
    enabled: true